import { writeFile } from 'node:fs'
import { resolve } from 'node:path'
import { definePreset, mergeConfigs } from 'unocss'
import * as themeConfig from '../src/theme'

export const presetTheme = definePreset<object, object>(() => {
  return {
    name: 'unocss-custom-preset-theme',
    ...mergeConfigs([
      themeConfig,
      {
        safelist: [
          (context) => {
            // 生成颜色名称
            const constDir = resolve(__dirname, '../src/constants')
            const colors = Object.keys(context.theme.colors ?? {})
            const colorConstantsFile = resolve(constDir, 'colors.ts')
            const content = [
              '// Generated by unocss theme plugin',
              '// Do not modify directly',
              `export const unocssPresetColors = ${JSON.stringify(colors, null, 2)} as const`,
            ].join('\n')

            writeFile(colorConstantsFile, content, 'utf-8', () => {})
            return []
          },
        ],
      },
    ]),
  }
})
