/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by uniapp-easycom
// biome-ignore lint: disable
export { }
declare module 'vue' {
  export interface GlobalComponents {
    WaterMark: (typeof import('../components/water-mark/water-mark.vue'))['default']
  }
}
